//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamGradesApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string TeacherLastName { get; set; }
        public string TeacherIdentificationNumber { get; set; }
        public Nullable<int> TeacherPassword { get; set; }
        public Nullable<int> LessonID { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
